config/routes.rb
Camera::Application.routes.draw do

  resources :orders do
	  collection do
	    get :confirm, :close, :place
      post :confirm, :pay
	    get :ali_callback
	    post :ali_callback
	  end 
  
	end
	
	resources :accounts do
		collection do
			get :login, :logout, :forgetpwd, :reset, :newpwd
			post :login, :forgetpwd, :newpwd
		end
	end
	
    match '/login' => 'accounts#login'
    match '/logout' => 'accounts#logout'

    match 'orders/close/:id' => 'orders#close'
    match 'orders/confirm/:id' => 'orders#confirm'
    match 'job/show' => 'jobs#show'
    match 'job/:id' => 'jobs#query'
    match 'faq' => 'misc#faq'
    match 'contact_us' => 'misc#contactus'

  root :to => 'misc#index'

end

app/models/order.rb
#encoding: utf-8

class Order < ActiveRecord::Base
  include ApplicationHelper
	belongs_to :user
	belongs_to :shipment
	has_many :order_histories
	has_many :order_items

	before_save :save_history
	before_create :gen_md5

  def save_history
  	oh = self.order_histories.build(:status => self.status)
  end

  def gen_md5
  	self.md5 = random_word(6)
  end
  
  def self.readable_status(status)
  	case status
		when 'new'
			return '下单'
		when 'paid'
			return '已付款'
		when 'pending'
			return "等待制作"
		when 'making'
			return "制作中..."
		when 'delivering'
			return "配送中"
		when 'received'
			return "已签收"
		end
	end
    
	def status_class
		case status
		when 'new'
			return 'orderlist-state4'
		when 'pending'
			return 'orderlist-state1'
		when 'making'
			return 'orderlist-state'
		when 'delivering'
			return 'orderlist-state2'
		when 'received'
			return 'orderlist-state3'
		end
	end
    
  def total_price
    sum = 0
    order_items.each do |oi|
      sum += oi.price.to_i
    end
    return sum
	end

end

app/controllers/orders_controller.rb
#encoding: utf-8

class OrdersController < ApplicationController
	before_filter :login_required, :only => [:index]

  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.orders

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find_by_md5(params[:id])
    
    if @order.nil?
    	if logged_in?
	    	@order = Order.find_by_id_and_user_id(params[:id], current_user.id)
    	else
    		store_location
    		authenticate_user!
  		end
  	end
  	
  	@job = Job.find(@order.order_items[0].job_id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  def new
  	@job = Job.find_by_name_and_status(params['job_id'], 'done')
  	raise ActiveRecord::RecordNotFound if @job.nil?
    @order = Order.new
    @user = User.new
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
    
  def place
    @job_id = params[:job_id]
    @job = Job.find_by_name(@job_id)
    if @job
      @job_style = 0
      @shipments = current_user.shipments if logged_in?
    else
      redirect_to '/job/show'
    end
  end
    
  def confirm
  	job_style = 0
  	
  	if !params[:id].blank?
  		@order = Order.find_by_md5(params[:id])
  		if @order.status != "new"
  			redirect_to :action => :show, :id => params[:id]
			end
		else
	    if !logged_in?
	      user = User.new(:email => params[:email], :password => params[:password], :password_confirmation => params[:password_confirmation])
	      begin
	        user.save!
	      rescue
		  		flash[:alert] = "该 Email 已存在，请登入或者选择其他 Email"
	        redirect_to :controller => :orders, :action => :place, :job_id => params[:job_id]
	        return
	      else
	      	self.current_user = user
	      end
	    end
	
	    @order = current_user.orders.build(:status => "new")
	    @job = Job.find_by_name(params[:job_id])
	    order_item = @order.order_items.build(:job_id => @job.id, :job_amount => params[:count], :job_style => job_style, :price => params[:count].to_i * Settings.PRODUCTS[job_style]["product_price"].to_f)
	
	    if !params[:name].blank?
	      shipment = current_user.shipments.build(:name => params[:name], :address => params[:address], :phone => params[:phone])
	      shipment.save
	    else
	      shipment = Shipment.find_by_id_and_user_id(params[:shipment_id], current_user.id)
	    end
	
	    @order.shipment_id = shipment.id
	    @order.save
    end
	end
    
	def pay
		id = params[:order_id]
		order = Order.find_by_md5_and_status(id, "new")
		
#		callback = Settings.HOST + "/orders/close/#{order.md5}"

    m = params["optionsRadios"]
    m = "" if m == 'alipay'
    @url = WebAlipayUtil.construct_auth_and_excute_url(Settings.PRODUCTS[0]["product_name"], order.id, order.total_price, m)
		redirect_to @url
	end
	
	def ali_callback
		logger = Logger.new('log/ali_callback.log')
		logger.info(params)		

    if not WebAlipayUtil.sign_valid?(params)
      logger.info("invalid")
      render :nothing => true
      return
    end

    out_trade_no = params["out_trade_no"]
    order_id = out_trade_no[out_trade_no.index(Settings.ORDER_PREFIX) + Settings.ORDER_PREFIX.size, out_trade_no.size - Settings.ORDER_PREFIX.size]

    order = Order.find(order_id)
    order.status = "paid"
    order.save
    
    Resque.enqueue(OrderNotification, "paid_notification", order.id)
    render :nothing => true
	end

  def close
    order_id = params[:id]
    @order = Order.find_by_md5(order_id)
    if @order.nil?
    	render :action => :failed
  	elsif @order.status == "new"
  		flash[:alert] = "付款未能成功，请重试！"
  		redirect_to :action => :confirm, :id => order_id
		elsif @order.status != "paid"
    	render :action => :failed
  	end
  end


end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/close.html.erb
<div class="padding-top68 indextbody">
  <div class="container">
    <div class="indent-warp">
      <div class="indent-step">
        <div class="col-xs-4 step-stopfirst"><span>1</span>
          <p>确认支付信息</p>
        </div>
        <div class="col-xs-4 step-stopfirst"><span>2</span>
          <p>选择一个支付方进行支付</p>
        </div>
        <div class="col-xs-4 step-stop"><span>3</span>
          <p>支付完成，等待收货</p>
        </div>
      </div>
      <div class="payment-pay">
      <div class="div-text"><img src="/images/numlist123-30.jpg" />支付成功！</div>
      <div class="detail-content">
      	<p>您可以在以下网址了解发货情况</p>
      	<p><% show_link = Settings.HOST + "/orders/#{@order.md5}" %>
				<a href='<%= show_link %>'><%= show_link %></a></p>
				</div>
      </div>
    </div>
  </div>
</div>

app/views/orders/confirm.html.erb
<% content_for :head do %>
<script>
$(document).ready(function() {
  $('#summit_btn').click(function() {
    $('#confirm_credit').submit();
  });
  $('input:radio').click( function(){
    $('#summit_btn').attr( 'disabled', false );
  });
});
</script>
<% end %>
<div class="padding-top68 indextbody">
  <div class="container">
    <div class="indent-warp">
      <div class="notification n_failure visible-xs visible-sm">您可能正在平板或者手机上浏览我们的网站，建议您在桌面电脑上进行支付操作</div>
      <% if !flash[:alert].blank? %>
      <div class="notification n_failure"><%= flash[:alert]%></div>
      <% end %>
      <div class="indent-step">
        <div class="col-xs-4 step-stopfirst"><span>1</span>
          <p>确认支付信息</p>
        </div>
        <div class="col-xs-4 step-stop"><span>2</span>
          <p>选择一个支付方进行支付</p>
        </div>
        <div class="col-xs-4"><span>3</span>
          <p>支付完成，等待收货</p>
        </div>
      </div>
      <div class="col-lg-12 padding-top20">
        <form id="confirm_credit" target="_blank" method="post" action="/orders/pay" accept-charset="UTF-8">
          <input type="hidden" name="order_id" id="order_id" value="<%= @order.md5 %>">
          <div class="payment-div">您需要支付<span> <%= @order.total_price %> </span>元，请选择支付方式</div>
          <div class="fn18 padding-top20">支付平台</div>
          <div class="payment-bank">
            <ul>
            <% for p in Settings.PAYMENT_PLATFORMS%>
              <li>
                <label>
                  <input type="radio" name="optionsRadios" id="optionsRadios1" value="<%= p.option_value %>">
                  <img src="/images/<%= p.image %>" /> </label>
              </li>
            <% end %>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="fn18">网银支付</div>
          <div class="payment-bank">
            <ul>
            <% for p in Settings.PAYMENT_BANKS%>
              <li>
                <label>
                  <input type="radio" name="optionsRadios" id="optionsRadios1" value="<%= p.option_value %>">
                  <img src="/images/<%= p.image %>" /> </label>
              </li>
            <% end %>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="text-center"> <button class="btn btn-primary btn-lg indent-btn2" data-toggle="modal" data-target="#myModal" id="summit_btn" disabled="true">去支付~</button></div>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="fn18">请在新打开的支付页面上完成付款</div>
      </div>
      <div class="modal-body">
        <div>
          如果您当前的浏览器无法付款，你可以换用其他浏览器，打开以下连接
          <br><% pay_link = Settings.HOST + "/orders/confirm/#{@order.md5}" %>
          <a href='<%= pay_link %>' target="_blank"><%= pay_link %></a>
        </div>
      </div>
      <div class="modal-footer">
      <button class="btn btn-primary indent-btn3" data-dismiss="modal" aria-hidden="true">重新选择</button>
      <a href="/orders/close/<%= @order.md5 %>"><button type="button" class="btn btn-primary indent-btn4">支付成功</button></a>
      </div>
    </div>
  </div>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/failed.html.erb
<div class="padding-top68 indextbody">
  <div class="container">
    <div class="indent-warp">
      <div class="indent-step">
        <div class="col-xs-4 step-stopfirst"><span>1</span>
          <p>确认支付信息</p>
        </div>
        <div class="col-xs-4 step-stopfirst"><span>2</span>
          <p>选择一个支付方进行支付</p>
        </div>
        <div class="col-xs-4 step-failed"><span>3</span>
          <p>支付完成，等待收货</p>
        </div>
      </div>
      <div class="payment-pay">
      <div class="div-text"><img src="/images/numlist123-36.jpg" />支付失败！</div>
      <div>您的订单异常</div>
      </div>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<% content_for :title do %>
<%= "您的订单 - " + Settings.TAGLINE %>
<% end %>
<div class="padding-top68 indextbody">
  <div class="container">
		<div class="indent-warp">
		<div class="orderlist-top fn18">您的订单</div>
		<div class="padding-top20 col-lg-12">
		<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-bordered indent-price text-center">
			<tr>
				<th width="80px" class="text-center">模型</th>
				<th class="text-center">品名</th>
				<th class="text-center" width="100px">状态</th>
				<th class="text-center">物流信息</th>
				<th class="text-center" width="130px">下单时间</th>
			</tr>
			<% @orders.each do |order| %>
		  <tr>
		  	<% job = Job.find(order.order_items[0].job_id)%>
		    <td><img src="/obj/<%= job.name %>/<%= job.name %>_t_s.jpg" /></td>
		    <td><a href="/orders/<%= order.md5.to_s %>"><%= Settings.PRODUCTS[order.order_items[0].job_style.to_i]["product_name"]%></a></td>
	      <td>
      	<% if order.status == 'new' %>
          <%= ('<span class="orderlist-state4"><a href="/orders/confirm/' + order.md5.to_s + '">去付款</a></span>').html_safe %>
        <% else
				order_class=order.status_class
				order_status=Order.readable_status(order.status)
				%>
        	<span class="<%=order_class%>"><%=order_status%></span>
      	<% end %>
        </td>
		    <td><%= order.shipment.mixed_str %>
		    	<% if order.status == "delivering" %>
		    	<br>物流号：<%= order.logistics %></td>
		    	<% end %>
		    <td><%= beautify_time(order.created_at) %></td>
		  </tr>
			<% end %>
		</table>
		</div>
		</div>
	</div>
</div>

app/views/orders/new.html.erb
<h1>New order</h1>

<form action="/orders/confirm" method="post">
<div class="extrainfo">
		<div class="e_item">
		<div class="e_left inline">邮箱：<span class="font_red">*</span></div>
		<div class="e_right inline">
		<input type="text" maxlength="40" class="e_name" id="email" name="email">
		<div class="e_item">
		<div class="e_left inline">密码：<span class="font_red">*</span></div>
		<div class="e_right inline">
		<input type="password" maxlength="40" class="e_name" id="password" name="password">
		<div class="e_item">
		<div class="e_left inline">确认密码：<span class="font_red">*</span></div>
		<div class="e_right inline">
		<input type="password" maxlength="40" class="e_name" id="email">
	</div>
		<div class="e_item">
		<div class="e_left inline">收货人姓名：<span class="font_red">*</span></div>
		<div class="e_right inline">
		<input type="text" maxlength="20" class="e_name" id="name" name="name">
	</div>
	<div class="e_item">
		<div class="e_left inline">地址：<span class="font_red">*</span></div>
		<div class="e_right inline">
		<input type="text" maxlength="20" class="e_name" id="address" name="address">
	</div>
	<div class="e_item">
		<div class="e_left inline">手机：<span class="font_red"></span></div>
		<div class="e_right inline">
		<input type="text" class="e_telphone" id="phone" name="phone">
		</div>
	</div>
			<input type="hidden" value="<%= @job.name %>" id="job_id" name="job_id">

<%= @job.name %><br>
<%= @job.status %>
<input type="submit" value="确认订单" name="commit" class="btn btn-primary">
</form>

app/views/orders/place.html.erb
<%content_for :head do%>
    <%= javascript_include_tag "parsley.min","parsley-messages.zh_cn"%>
<%end%>
<div class="padding-top68 indextbody">
    <div class="container">
      <div class="indent-warp">
	      <div class="notification n_failure visible-xs visible-sm">您可能正在平板或者手机上浏览我们的网站，建议您在桌面电脑上继续操作</div>
	      <% if !flash[:alert].blank? %>
	      <div class="notification n_failure"><%= flash[:alert]%></div>
	      <% end %>
        <div class="indent-step">
          <div class="col-xs-4 step-stop"><span>1</span>
              <p>确认支付信息</p>
          </div>
          <div class="col-xs-4 step-bg"><span>2</span>
              <p>选择一个支付方进行支付</p>
          </div>
          <div class="col-xs-4 step-bg"><span>3</span>
              <p>支付完成，等待收货</p>
          </div>
        </div>
      <div class="padding-15">
        <form id="form_order" action="/orders/confirm" method="post">
          <% if logged_in? %>
              <div class="col-sm-8" id="div_login">
                  <div class="login-warp">
                    <div class="fn18 padding-top20 ">收货信息</div>
                    <script type="text/javascript">
                    function checkMode(){
                      if($('input:radio[value=new]:checked').length){
                      	$("#login-address-form").slideDown();
                        $('input[name=name]').parsley('addConstraint',{required:true});
                        $('input[name=phone]').parsley('addConstraint',{required:true,regexp:'1\\d{10}'});
                        $('input[name=address]').parsley('addConstraint',{required:true});
                      }
                      else{
                      	$("#login-address-form").slideUp();
                        $('input[name=name]').parsley('removeConstraint','required');
                        $('input[name=name]').next().html('');
                        $('input[name=phone]').parsley('removeConstraint','required');
                        $('input[name=phone]').parsley('removeConstraint','regexp');
                        $('input[name=phone]').next().html('');
                        $('input[name=address]').parsley('removeConstraint','required');
                        $('input[name=address]').next().html('');
                      }
                    }
                    </script>
                    <span id="shipment_id_validation"></span>
                    <!--地址一-->
                    <% @shipments.each do |shipment| %>
                    <div class="login-sites">
                      <input type="radio" name="shipment_id" id="shipment_<%= shipment.id %>" value="<%= shipment.id%>" onchange="checkMode()" parsley-required="true" parsley-error-container="#shipment_id_validation" parsley-required-message="必须至少选择一项">
                      <div class="div-site">
                        <label for="shipment_<%= shipment.id %>"><%= shipment.name %><br><%= shipment.phone %><br><%= shipment.address %></label>
                      </div>
                    </div>
                    <% end %>
                    <div class="login-sites">
                      <input type="radio" name="shipment_id" id="shipment_new" value="new" onchange="checkMode()">
                      <div class="login-addsite"><label for="shipment_new">添加一个新的地址</label></div>
                    </div>
                    <div id="login-address-form" style="display:none;">
                    <div class="indent-inputin">
                      <input type="text" class=" indent-input2" name="name"  placeholder="姓名" onclick="$('#shipment_new').click();" parsley-error-container="#name_validation" parsley-validation-minlength="1" parsley-trigger="keyup" parsley-required-message="请输入你的姓名">
                      <span></span>
                      <span id="name_validation"></span>
                    </div>
                    <div class="indent-inputin">
                      <input type="text" class=" indent-input2" name="phone"  placeholder="手机号码" onclick="$('#shipment_new').trigger('click');" parsley-error-container="#phone_validation" parsley-validation-minlength="11" parsley-trigger="keyup" parsley-required-message="请输入手机号码" parsley-regexp-message="手机号码有误">
                      <span></span>
                      <span id="phone_validation"></span>
                    </div>
                    <div class="indent-inputin">
                      <input type="text" class=" indent-input3" name="address" placeholder="收货地址" onclick="$('#shipment_new').trigger('click');" parsley-error-container="#address_validation" parsley-validation-minlength="1" parsley-trigger="keyup" parsley-required-message="请输入收货地址">
                      <span></span>
                      <span id="address_validation"></span>
                    </div>
                    <script type="text/javascript">
                      $('input[type=radio]:first').click();
                      $('input[name=name],input[name=phone],input[name=address]').keydown(function(e){
                        if(e.which!=9&&e.which!=13&&e.which!=32)
                          $('#shipment_new').click();
                      });
                    </script>
                  </div>
                  </div>
              </div>
          <div class="col-sm-4">
            <div class="indent-place " style="cursor:pointer">
              <a href="/logout?return_to=<%= CGI.escape('/orders/place?job_id=' + @job_id) %>">您不是<%= current_user.email%>？<br>
              点击这里注册新用户</a>
            </div>
          </div>

        
        <% else %>
        
            <script type="text/javascript">var checkMode=undefined;</script>
              <div class="col-sm-8" id="div_register">
                <div class="login-warp">
                    <div class="fn18">账户注册</div>
                    <div class="indent-inputin">
                      <input type="text" class="indent-input" id="email" name="email" placeholder="tale@mail.com" parsley-required="true" parsley-type="email" parsley-trigger="change" parsley-error-container="#register_email_validation"/>
                      <span></span>
                      <span id="register_email_validation"></span>
                    </div>
                    <div class="indent-inputin">
                      <input type="password" class="indent-input" id="password" name="password" placeholder="请输入密码" parsley-required="true" parsley-validation-minlength="1" parsley-minlength="6" parsley-trigger="change" parsley-error-container="#register_password_validation" parsley-minlength-message="密码应至少6位"/>
                      <span></span>
                      <span id="register_password_validation"></span>
                    </div>
                    <div class="indent-inputin">
                      <input type="password" class="indent-input" id="password_confirmation" name="password_confirmation" placeholder="请确认密码" parsley-required="true" parsley-equalto="#password" parsley-validation-minlength="1" parsley-trigger="change" parsley-error-container="#register_confirm_validation" parsley-equalto-message="密码不一致"/>
                      <span></span>
                      <span id="register_confirm_validation"></span>
                    </div>
                    <div class="fn18 padding-top20">收货信息</div>
                    <div class="indent-inputin">
                      <input type="text" class="indent-input2" id="name" name="name" placeholder="姓名" parsley-required="true"  parsley-error-container="#name_validation" parsley-validation-minlength="1" parsley-trigger="keyup" parsley-required-message="请输入你的姓名"/>
                      <span></span>
                      <span id="name_validation"></span>
                    </div>
                    <div class="indent-inputin">
                      <input type="text" class="indent-input2" id="phone" name="phone" placeholder="手机号码" parsley-required="true"  parsley-error-container="#phone_validation" parsley-regexp="1\d{10}" parsley-trigger="keyup" parsley-required-message="请输入手机号码" parsley-regexp-message="手机号码有误"/>
                      <span></span>
                      <span id="phone_validation"></span>
                    </div>
                    <div class="indent-inputin">
                      <input type="text" class="indent-input3" id="address" name="address" placeholder="收货地址" parsley-required="true"  parsley-error-container="#address_validation" parsley-validation-minlength="1" parsley-trigger="keyup" parsley-required-message="请输入收货地址"/>
                      <span></span>
                      <span id="address_validation"></span>
                    </div>
                  </div>
              </div>
              <div class="col-sm-4">
                <div class="indent-place" style="cursor:pointer">
                  <a href="/login?return_to=<%= CGI.escape('/orders/place?job_id=' + @job_id) %>">已经有了账户？点这里登入</a>
                </div>
              </div>
          <% end %>
              <p class="clearfix"></p>
              <div class="col-lg-12">
                  <div class="indent-OrderInfo">订单信息</div>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-bordered indent-price">
                      <tr>
                          <th>名称</th>
                          <th width="15%" class="text-center">数量</th>
                          <th width="15%" class="text-center">单价</th>
                      </tr>
                      <tr>
                          <td><input type="hidden" id="job_id" name="job_id" value="<%=@job_id%>"/><img src="/obj/<%= @job.name %>/<%= @job.name %>_t_s.jpg" /><span class="names">品名：<%= Settings.PRODUCTS[@job_style]["product_name"] %></span></td>
                        <td>
                          <div class="alipay-divs">
                            <script type="text/javascript">
                              function changeCount(d){
                                var v=parseInt($('#count').val())+d;
                                if(v>=10){
                                  v=10;
                                  $('#span_plus').css('cursor','not-allowed');
                                  $('#span_minus').css('cursor','auto');
                                }
                                else if(v<=1){
                                  v=1;
                                  $('#span_plus').css('cursor','auto');
                                  $('#span_minus').css('cursor','not-allowed');
                                }
                                else{
                                  $('#span_plus').css('cursor','auto');
                                  $('#span_minus').css('cursor','auto');
                                }
                                $('#count').val(v);
                                updateTotal(v);
                              }
                            </script>
                            <span class="span-jian" id="span_minus" onclick="changeCount(-1)"></span>
                            <input id="count" name="count" type="text"  class="span-input" value="1" onchange="changeCount(0)"/>
                            <span class="span-jia" id="span_plus" onclick="changeCount(1)"></span>
                          </div>
                        </td>
                        <script type="text/javascript">
                          function updateTotal(v){
                            $('#total').html(' '+v*<%= Settings.PRODUCTS[@job_style]["product_price"] %>+' ');
                          }
                          changeCount(0);
                        </script>
                          <td class="text-center fn18"><%= Settings.PRODUCTS[@job_style]["product_price"] %> 元</td>
                      </tr>
                  </table>
                  <table class="indent-inputin"><tr><td><span id="job_id_validation_img"></span></td><td id="job_id_validation"></td></tr></table>
                  <p class="text-right">共计：<span id="total" class="indent-total"> <%= Settings.PRODUCTS[@job_style]["product_price"] %> </span>元</p>
                  <div class="text-center"> <button type="submit" class="btn btn-primary btn-lg indent-btn2">确认订单</button>
                  </div>
              </div>
          </form>
          </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#form_order').parsley({ successClass: '', errorClass: 'indent-inputred' });
    $('#form_order').parsley( 'addListener', {
    onFieldSuccess: function ( elem ) {
        if(elem.attr('type')!='checkbox'&&elem.attr('type')!='radio')
            elem.next().html('<img src="/images/numlist123-18.jpg"  />');
        else if(elem.attr('type')=='checkbox')
            $('#job_id_validation_img').html('<img src="/images/numlist123-18.jpg"  />');
        return true;
    },
    onFieldError: function ( elem ) {
        if(elem.attr('type')!='checkbox'&&elem.attr('type')!='radio')
            elem.next().html('<img src="/images/numlist123-19.jpg"  />');
        else if(elem.attr('type')=='checkbox')
            $('#job_id_validation_img').html('<img src="/images/numlist123-19.jpg"  />');
        return false;
    }
} );
  if(checkMode)checkMode();
</script>

app/views/orders/success.html.erb
<div class="padding-top68">
  <div class="container">
    <div class="indent-warp">
      <div class="indent-step">
        <div class="col-xs-4 step-stopfirst"><span>1</span>
          <p>确认支付信息</p>
        </div>
        <div class="col-xs-4 step-stopfirst"><span>2</span>
          <p>选择一个支付方进行支付</p>
        </div>
        <div class="col-xs-4 step-stop"><span>3</span>
          <p>支付完成，等待收货</p>
        </div>
      </div>
      <div class="payment-pay">
      <div class="div-text"><img src="/images/numlist123-30.jpg" />支付成功！</div>
      <div>您的订单20cm 人偶预计2014.5.6日送达<br />

3s过后返回<a href="#">订单列表</a></div>
      </div>
    </div>
  </div>
</div>